### ISSUE TITLE
Coccinelle fails to detect function

### ISSUE THREAD

**Issue by shakkhar** [coccinelle/coccinelle#150]
I have this very simple coccinelle script which, I expect, should produce a list of all function definitions in a given C file:
```myscript.cocci
virtual report

@ match @
identifier cb;
position p;
@@

cb@p(...)
{
...
}

@script:python depends on report@
cb << match.cb;
p << match.p;
@@

msg='function definition found: %s' % (cb)
coccilib.report.print_report(p[0], msg)
```
I ran the script on `kernel/bpf/core.c` in the linux kernel source code (cloned from git, revision 380ef2c9ad4fdd5fdd81055857be21ae5f581877) with the following command:
```
make coccicheck COCCI=myscript.cocci MODE=report M=kernel/bpf/core.c
```
The command produces the following output:
https://gist.github.com/shakkhar/0000c3e7764cf65e3e3df63a1679a812

Note the conspicuous absence of `___bpf_prog_run`. This, I think, is the only function that my script failed to detect. Is this a bug in coccinelle or in my script? The script I shared above is a stripped down version that reproduces a production issue. Incidentally, if we get rid of the entire function body of `___bpf_prog_run`, then coccinelle does detect the function definition.

I built spatch from source:
```
$ spatch --version
spatch version 1.0.7-00124-gc2ed486 compiled with OCaml version 4.02.3
Flags passed to the configure script: --disable-pcre-syntax --disable-parmap
OCaml scripting support: yes
Python scripting support: yes
Syntax of regular expresssions: Str
```
Thanks for making coccinelle :100: :+1:

**Comment by JuliaLawall** [comment]
On Fri, 14 Dec 2018, Shakkhar wrote:

>
> I have this very simple coccinelle script which, I expect, should produce a
> list of all function definitions in a given C file:
>
> virtual report
>
> @ match @
> identifier cb;
> position p;
> @@
>
> cb@p(...)
> {
> ...
> }
>
> @script:python depends on report@
> cb << match.cb;
> p << match.p;
> @@
>
> msg='function definition found: %s' % (cb)
> coccilib.report.print_report(p[0], msg)

The script looks fine.  All of the information that you provide suggests
that the problem is just that the missed function is not parseable.  You
can run spatch --parse-c file.c.  This will show you where the parse
errors are.  It found an error on the line marked BAD and then it skipped
parsing all of the lines marked bad.

If you don't mind, we prefer discussions on the mailing list rather than
github:

cocci@systeme.lip6.fr

If you will use Coccinelle a lot, you may want to subscribe:

http://coccinelle.lip6.fr/contact.php

julia
