### ISSUE TITLE
Improve pretty-printing for a variable initalisation in a Linux driver function

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#240]
I have tried further script variants out for the semantic patch language (according to the software combination “Coccinelle 1.0.8-00177-g28737419”) together with [a selected source file](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/interconnect/imx/imx.c?id=7059c2c00a2196865c2139083cbef47cd18109b6#n78 "Update candidate: imx_icc_node_init_qos()").

```cocci
@replacement@
expression e;
identifier i;
statement s;
type t;
@@
-t *i = NULL;
 ... when any
     when != i
 if (...)
    s
 else
 {
+   t*
    i = e(...);
 ... when any
 }
```

Test result:
```
elfring@Sonne:~/Projekte/Linux/next-patched> spatch ~/Projekte/Coccinelle/janitor/reduce_scope_for_a_variable.cocci drivers/interconnect/imx/imx.c
…
@@ -89,7 +88,7 @@ static int imx_icc_node_init_qos(struct
 		dev_dbg(dev, "icc node %s[%d] is main noc itself\n",
 			node->name, node->id);
 	} else {
-		dn = of_parse_phandle(dev->of_node, adj->phandle_name, 0);
+		struct device_node *dn = of_parse_phandle(dev->of_node, adj->phandle_name, 0);
 		if (!dn) {
 			dev_warn(dev, "Failed to parse %s\n",
 				 adj->phandle_name);
```

The line length is 93 characters for the added variable definition.

-----

```cocci
@replacement3@
expression e;
expression list el;
identifier i;
statement s;
type t;
@@
-t *i = NULL;
 ... when any
     when != i
 if (...)
    s
 else
 {
-   i = e(el)
+   t *i = e(el)
 ;
 ... when any
 }
```

Another test result:
```
elfring@Sonne:~/Projekte/Linux/next-patched> spatch ~/Projekte/Coccinelle/janitor/reduce_scope_for_a_variable3.cocci drivers/interconnect/imx/imx.c
…
@@ -89,7 +88,9 @@ static int imx_icc_node_init_qos(struct
 		dev_dbg(dev, "icc node %s[%d] is main noc itself\n",
 			node->name, node->id);
 	} else {
-		dn = of_parse_phandle(dev->of_node, adj->phandle_name, 0);
+		struct device_node * dn = of_parse_phandle(dev->of_node,
+							   adj->phandle_name,
+							   0);
 		if (!dn) {
 			dev_warn(dev, "Failed to parse %s\n",
 				 adj->phandle_name);
```

:thinking: Is the space character unwanted between the asterisk and the variable name for such a code adjustment?
(Do I need to fix this glitch by [passing the command parameter “`--smpl-spacing`”](https://github.com/coccinelle/coccinelle/blob/287374196da8c7cfd169e721a2d23f1e462422f1/docs/manual/spatch_options.tex#L627 "Description for command parameters")?)

**Comment by JuliaLawall** [comment]
On Sun, 6 Dec 2020, Markus Elfring wrote:

>
> I have tried further script variants out for the semantic patch language
> (according to the software combination “Coccinelle 1.0.8-00177-g28737419”)
> together with a selected source file.
>
> @replacement@
> expression e;
> identifier i;
> statement s;
> type t;
> @@
> -t *i = NULL;
>  ... when any
>      when != i
>  if (...)
>     s
>  else
>  {
> +   t*
>     i = e(...);
>  ... when any
>  }
>
> Test result:
>
> elfring@Sonne:~/Projekte/Linux/next-patched> spatch ~/Projekte/Coccinelle/ja
> nitor/reduce_scope_for_a_variable.cocci drivers/interconnect/imx/imx.c
> …
> @@ -89,7 +88,7 @@ static int imx_icc_node_init_qos(struct
>  		dev_dbg(dev, "icc node %s[%d] is main noc itself\n",
>  			node->name, node->id);
>  	} else {
> -		dn = of_parse_phandle(dev->of_node, adj->phandle_name, 0);
> +		struct device_node *dn = of_parse_phandle(dev->of_node, adj->phandle_name,
> 0);
>  		if (!dn) {
>  			dev_warn(dev, "Failed to parse %s\n",
>  				 adj->phandle_name);
>
> The line length is 93 characters for the added variable definition.
>
> ____________________________________________________________________________
>
> @replacement3@
> expression e;
> expression list el;
> identifier i;
> statement s;
> type t;
> @@
> -t *i = NULL;
>  ... when any
>      when != i
>  if (...)
>     s
>  else
>  {
> -   i = e(el)
> +   t *i = e(el)
>  ;
>  ... when any
>  }
>
> Another test result:
>
> elfring@Sonne:~/Projekte/Linux/next-patched> spatch ~/Projekte/Coccinelle/ja
> nitor/reduce_scope_for_a_variable3.cocci drivers/interconnect/imx/imx.c
> …
> @@ -89,7 +88,9 @@ static int imx_icc_node_init_qos(struct
>  		dev_dbg(dev, "icc node %s[%d] is main noc itself\n",
>  			node->name, node->id);
>  	} else {
> -		dn = of_parse_phandle(dev->of_node, adj->phandle_name, 0);
> +		struct device_node * dn = of_parse_phandle(dev->of_node,
> +							   adj->phandle_name,
> +							   0);
>  		if (!dn) {
>  			dev_warn(dev, "Failed to parse %s\n",
>  				 adj->phandle_name);
>
> 🤔 Is the space character unwanted between the asterisk and the variable
> name for such a code adjustment?

This issue is resolved by the folowing patch.  Unfortunately, there is
something wrong with our CI, and so it's not likely to be available in
github until next year.

julia

diff --git a/parsing_c/unparse_c.ml b/parsing_c/unparse_c.ml
index ca3de697..2cb1bfe0 100644
--- a/parsing_c/unparse_c.ml
+++ b/parsing_c/unparse_c.ml
@@ -1019,7 +1019,7 @@ code and C code *)
 let adjust_eat_space toks =
   let rec loop = function
     | [] -> []
-    | EatSpace2 :: x :: rest when is_space x -> loop rest
+    | EatSpace2 :: x :: rest when is_space x || is_added_space x -> loop rest
     | EatSpace2 :: rest -> loop rest
     | x :: xs -> x :: loop xs in
   loop toks
diff --git a/tests/replacement3.c b/tests/replacement3.c
new file mode 100644
index 00000000..da4f05c3
--- /dev/null
+++ b/tests/replacement3.c
@@ -0,0 +1,6 @@
+int main() {
+  int *i;
+  {
+   i = e(el);
+  }
+}
diff --git a/tests/replacement3.cocci b/tests/replacement3.cocci
new file mode 100644
index 00000000..2a2c92bc
--- /dev/null
+++ b/tests/replacement3.cocci
@@ -0,0 +1,12 @@
+@replacement3@
+expression e;
+expression list el;
+identifier i;
+type t;
+@@
+-t *i;
+ {
+-   i = e(el)
++   t *i = e(el)
+ ;
+ }
diff --git a/tests/replacement3.res b/tests/replacement3.res
new file mode 100644
index 00000000..1a526fb1
--- /dev/null
+++ b/tests/replacement3.res
@@ -0,0 +1,5 @@
+int main() {
+  {
+   int *i = e(el);
+  }
+}

**Comment by elfring** [comment]
>This issue is resolved by the folowing patch.

Thanks for such helpful feedback.

Would you like to adjust anything also for the other mentioned change approach?

**Comment by elfring** [comment]
See also:
[improve EatSpace implementation](https://github.com/coccinelle/coccinelle/commit/b3d20ef224a4997dc44fcc17f461a77471a91c4f "Software update")
