### ISSUE TITLE
Tag 1.1.0 changed?

### ISSUE THREAD

**Issue by evdenis** [coccinelle/coccinelle#268]
Hi, did you change tag 1.1.0?
Installation with opam fails with bad checksum message:
```
OpamSolution.Fetch_fail("https://github.com/coccinelle/coccinelle/archive/1.1.0.tar.gz (Bad checksum, expected md5=4be4e417fc12a3fd333825192a2d2a4f)")
```

**Comment by evdenis** [comment]
Anyway, I'm going to update checksums in opam repository to fix the build.

**Comment by JuliaLawall** [comment]
On Mon, 8 Nov 2021, Denis Efremov wrote:

>
> Anyway, I'm going to update checksums in opam repository to fix the build.

OK, thanks.

**Comment by thierry-martinez** [comment]
I already heard from some people that they observed that tarballs generated with tags were not reproducible and advocated for building the tarballs ourselves and uploading them as binaries (cf. https://discuss.ocaml.org/t/publishing-to-opam/6112/2 for instance), but it was for GitHub and I did never observe that with Gitlab before. If it happens again, we should upload the tarball in Gitlab ourselves instead of relying on the tarball.

**Comment by evdenis** [comment]
PR with new checksums
https://github.com/ocaml/opam-repository/pull/19963/files
