### ISSUE TITLE
Same SmPL produces 2 or 3 matches if in apython script or not

### ISSUE THREAD

**Issue by alessandrocarminati** [coccinelle/coccinelle#278]
My objective is to recover a given function's second argument type called somewhere in a c file.
I wrote a SmPL script that should match the function call and its argument declaration, both in local variables and in host function formal arguments.
I then enriched my script by using python to have the output.
Because it wouldn't give me the results I expected, I tried to strip off the python part, and there, my something unexpected. 
The SmPL script with python matched 3 of the 4 function calls into the c file.
The same SmPL script alone matches only two of the 4 function calls of the same c file.
here the SmPL with python
```
@script:python@
@@
import sys
cnt=0

@ idfind @ 
type FT, IDT;
identifier FN;
type L4;
identifier I =~ "dma_map_single";
identifier ID, SF;
expression  A1, A3, A4, NA;
@@

(
* FT FN( ... ){
 ...
(
* IDT ID;
|
* IDT ID=NA;
)
 ...
( 
* I( A1, ID -> SF, A3, A4 )
|
* I( A1, ID, A3, A4 )
)
 ...
}
|
* FT FN( ..., IDT ID, ... ){
 ...
(
*  I( A1, ID -> SF, A3, A4 )
|
*  I( A1, ID, A3, A4 )
)
 ...
 }
)

@script:python @ 
fn << idfind.FN;
f << idfind.SF; 
ty << idfind.IDT;
id << idfind.ID;
@@
print('identifier="{:s}" type="{:s}" field="{:s}" detected in function "{:s}"'.format(id,ty,f,fn))
	
cnt+=1

@script:python@
@@
if cnt>0 :
	sys.exit(0)
sys.exit(1)
```
here what's happen when I launch it:
```
$ spatch  -sp_file py.cocci  /home/alessandro/src/linux-git/drivers/net/wireless/ath/ath11k/dp_rx.c
init_defs_builtins: /usr/local/bin/lib/coccinelle/standard.h
warning: idfind: metavariable L4 not used in the - or context code
HANDLING: /home/alessandro/src/linux-git/drivers/net/wireless/ath/ath11k/dp_rx.c
identifier="skb" type="struct sk_buff *" field="data" detected in function "ath11k_dp_rx_alloc_mon_status_buf"
identifier="defrag_skb" type="struct sk_buff *" field="data" detected in function "ath11k_dp_rx_h_defrag_reo_reinject"
identifier="skb" type="struct sk_buff *" field="data" detected in function "ath11k_dp_rxbufs_replenish"
```
and this is the SmPL without python:
```
@ idfind @ 
type FT, IDT;
identifier FN;
type L4;
identifier I =~ "dma_map_single";
identifier ID, SF;
expression  A1, A3, A4, NA;
@@

(
* FT FN( ... ){
 ...
(
* IDT ID;
|
* IDT ID=NA;
)
 ...
( 
* I( A1, ID -> SF, A3, A4 )
|
* I( A1, ID, A3, A4 )
)
 ...
}
|
* FT FN( ..., IDT ID, ... ){
 ...
(
*  I( A1, ID -> SF, A3, A4 )
|
*  I( A1, ID, A3, A4 )
)
 ...
 }
)
```
Here its execution:
```
$ spatch  -sp_file nopy.cocci /home/alessandro/src/linux-git/drivers/net/wireless/ath/ath11k/dp_rx.c
init_defs_builtins: /usr/local/bin/lib/coccinelle/standard.h
warning: idfind: metavariable L4 not used in the - or context code
HANDLING: /home/alessandro/src/linux-git/drivers/net/wireless/ath/ath11k/dp_rx.c
diff = 
--- /home/alessandro/src/linux-git/drivers/net/wireless/ath/ath11k/dp_rx.c
+++ /tmp/cocci-output-452583-0d1fae-dp_rx.c
@@ -2836,11 +2836,6 @@ static void ath11k_dp_rx_update_peer_sta
 	arsta->rx_duration = rx_stats->rx_duration;
 }
 
-static struct sk_buff *ath11k_dp_rx_alloc_mon_status_buf(struct ath11k_base *ab,
-							 struct dp_rxdma_ring *rx_ring,
-							 int *buf_id)
-{
-	struct sk_buff *skb;
 	dma_addr_t paddr;
 
 	skb = dev_alloc_skb(DP_RX_BUFFER_SIZE +
@@ -2855,9 +2850,6 @@ static struct sk_buff *ath11k_dp_rx_allo
 			 skb->data);
 	}
 
-	paddr = dma_map_single(ab->dev, skb->data,
-			       skb->len + skb_tailroom(skb),
-			       DMA_FROM_DEVICE);
 	if (unlikely(dma_mapping_error(ab->dev, paddr)))
 		goto fail_free_skb;
 
@@ -3361,9 +3353,6 @@ static int ath11k_dp_rx_h_defrag(struct
 	return 0;
 }
 
-static int ath11k_dp_rx_h_defrag_reo_reinject(struct ath11k *ar, struct dp_rx_tid *rx_tid,
-					      struct sk_buff *defrag_skb)
-{
 	struct ath11k_base *ab = ar->ab;
 	struct ath11k_pdev_dp *dp = &ar->dp;
 	struct dp_rxdma_ring *rx_refill_ring = &dp->rx_refill_buf_ring;
@@ -3403,9 +3392,6 @@ static int ath11k_dp_rx_h_defrag_reo_rei
 	/* change msdu len in hal rx desc */
 	ath11k_dp_rxdesc_set_msdu_len(ab, rx_desc, defrag_skb->len - hal_rx_desc_sz);
 
-	paddr = dma_map_single(ab->dev, defrag_skb->data,
-			       defrag_skb->len + skb_tailroom(defrag_skb),
-			       DMA_TO_DEVICE);
 	if (dma_mapping_error(ab->dev, paddr))
 		return -ENOMEM;
```
Thank you for any help.

**Comment by JuliaLawall** [comment]
On Thu, 23 Dec 2021, Alessandro Carminati wrote:

>
> My objective is to recover a given function's second argument type called somewhere in a c file.
> I wrote a SmPL script that should match the function call and its argument declaration, both in local variables and in host function formal arguments.
> I then enriched my script by using python to have the output.
> Because it wouldn't give me the results I expected, I tried to strip off the python part, and there, my something unexpected.
> The SmPL script with python matched 3 of the 4 function calls into the c file.
> The same SmPL script alone matches only two of the 4 function calls of the same c file.
> here the SmPL with python

The rule is more complicated than necessary.  Coccinelle has access to
information about types directly.

@r@
type t;
expression e1;
t e2;
identifier fld;
@@

(
dma_map_single(e1,e2->fld,...)
|
dma_map_single(e1,e2,...)
)

@script:python@
t << r.t;
fld << r.fld;
@@

print "structure case"
print t
print fld
cocci.include_match(false)

@script:python@
t << r.t;
fld << r.fld;
@@

print "non structure case"
print t

julia

**Comment by JuliaLawall** [comment]
The reason for getting fewer results without python has to do with the
semantics of ... and the quantification of ID.

First, A ... B means that neither A nor B should be matched by the ...
That is, one should get the closest A and B.
This constraint can be avoided by putting when any after the ...

Second, when ID is not used by a subsequent rule, it is quantified over as
small a region as possible, allowing it to take different values on
different paths through the code. (no python case)

When ID is used by a subsequnt rule, it is quantified over the whole rule,
so that all occurrences have to match the same code, so that the
subsequent rule receives only one value per match. (with python case)

In the no python case, there is something like:

A ... (exists ID. B)

and in the with python case:

exists ID. (A ... B)

In the no python case, however, we have to make a constraint on the ... to
take care of the first issue.  The problem is that that constraint has to
refer to ID, but ID is not yet bound.  So we just make another one:

A (exists ID. ...) (exists ID. B)

The first ID, however, can be freely different than the second one.

Thus, in the no python case, the rule says that there can be no variable
declaration at all before the matched one, while in the with python case
the rule says that there can be no variable declaration that matches the
variable used in the call to dma_map_single.

I hope that is comprehensible.  In any case, the solution proposed in the
other message is the better one.

julia

**Comment by JuliaLawall** [comment]
On Thu, 23 Dec 2021, Alessandro Carminati wrote:

>
> My objective is to recover a given function's second argument type called somewhere in a c file.
> I wrote a SmPL script that should match the function call and its argument declaration, both in local variables and in host function formal arguments.
> I then enriched my script by using python to have the output.
> Because it wouldn't give me the results I expected, I tried to strip off the python part, and there, my something unexpected.
> The SmPL script with python matched 3 of the 4 function calls into the c file.

The reason why it is only 3 of 4 is because the python rule uses the
metavariable SF.  In one of the cases there is no value for SF.  Python
rules require all inherited variables to be defined.

One approach to deal with this problem is to have multiple python rules,
as illustrated in my first response.

Another approach is to provide a default value for variables that may be
missing.  For example, in your case, you could put:

f << idfind.SF = "none";

julia

**Comment by alessandrocarminati** [comment]
Thank you for the detailed explanation!
Once you've read it, everything makes sense.
Really helpful.
Happy winter holidays.
