### ISSUE TITLE
Writing a rule which detect calls to functions, but omits calls to static inline functions.

### ISSUE THREAD

**Issue by 0xfk0** [coccinelle/coccinelle#304]
Assume following example:
```
static inline f(int x) { return x + 1; }

int g(int x);

int h(int x)
{
        X(f(x));        // must not match
        X(g(x));        // must match
}
```

I want to match only expressions like `X(f(x))`, where f is a static inline function. For this I have written the following rule:
```
@static_inline_func@
type T;
identifier F;
@@
static inline T F(...) { ... }

@assert_func_only@
position P;
identifier static_inline_func.F;
identifier E;
@@
	\(
		X(..., <+... F(...) ...+>, ...);
	\|
		X(..., <+... E(...) ...+>, ...)@P
	\)


@assert_func@
position assert_func_only.P;
identifier assert_func_only.E;
@@
	X(..., <+... E(...) ...+>, ...)@P

@script:python@
func << assert_func_only.E; pos << assert_func_only.P;
@@
print("%s:%u: %s" % (pos[0].file, int(pos[0].line), func))
```

This rule works as expected, but only until the second static inline function is not defined. For example, for the following code rule is wrong:
```
static inline f(int x) { return x + 1; }

static inline m(int x) { return x; }

int g(int x);

int h(int x)
{
        X(f(x));        // must not match
        X(g(x));        // must match
        return x;
}
```

Output will be following:
```
init_defs_builtins: /usr/local/lib/coccinelle/standard.h
HANDLING: testc.c
testc.c:10: f
testc.c:11: g
```

As I understood, coccinelle tries to apply each possible match of `static_inline_func` to `assert_func_only` rule. So `static_inline_func.F` will have both values, `f` and `m`. As a result, the expression `X(f(x))` will not be detected as a call to static inline function in a case, when `static_inline_func.F` equal to `m`.

How can I rewrite the rules listed above to detect all calls to static inline functions, independently of function name?
It is possible?

**Comment by JuliaLawall** [comment]
On Tue, 11 Apr 2023, Kirill Frolov wrote:

>
> Assume following example:
>
> static inline f(int x) { return x + 1; }
>
> int g(int x);
>
> int h(int x)
> {
>         X(f(x));        // must not match
>         X(g(x));        // must match
> }
>
> I want to match only expressions like X(f(x)), where f is a static inline function. For this I have written the following rule:
>
> @static_inline_func@
> type T;
> identifier F;
> @@
> static inline T F(...) { ... }
>
> @assert_func_only@
> position P;
> identifier static_inline_func.F;
> identifier E;
> @@
> 	\(
> 		X(..., <+... F(...) ...+>, ...);
> 	\|
> 		X(..., <+... E(...) ...+>, ...***@***.***
> 	\)
>
>
> @assert_func@
> position assert_func_only.P;
> identifier assert_func_only.E;
> @@
> 	X(..., <+... E(...) ...+>, ...***@***.***
>
> @script:python@
> func << assert_func_only.E; pos << assert_func_only.P;
> @@
> print("%s:%u: %s" % (pos[0].file, int(pos[0].line), func))
>
> This rule works as expected, but only until the second static inline function is not defined. For example, for the following code rule is wrong:
>
> static inline f(int x) { return x + 1; }
>
> static inline m(int x) { return x; }
>
> int g(int x);
>
> int h(int x)
> {
>         X(f(x));        // must not match
>         X(g(x));        // must match
>         return x;
> }
>
> Output will be following:
>
> init_defs_builtins: /usr/local/lib/coccinelle/standard.h
> HANDLING: testc.c
> testc.c:10: f
> testc.c:11: g
>
> As I understood, coccinelle tries to apply each possible match of static_inline_func to assert_func_only rule. So static_inline_func.F will have both values, f and m. As a result, the expression X(f(x)) will not be detected as a call to static inline
> function in a case, when static_inline_func.F equal to m.

This statement is correct.

>
> How can I rewrite the rules listed above to detect all calls to static inline functions, independently of function name?
> It is possible?

You need to use python or ocaml code.  In OCaml, it could be:

@initialize:ocaml@
@@

let statics = ref []

let upd f = static := f :: !statics

let mem f = List.mem f !statics

@script:ocaml@
@@

static := []

@@
identifier f : script:ocaml() { upd f };
@@

static inline f(...) { ... }

@@
identifier f : script:ocaml() { mem f };
@@

// match where you want to check that f is some static inline function

---------------------

I tend to put only function calls in the bits of script calls in the
metavariable declarations, because there are some limitations to the
parser.

The () after script:ocaml can refer to previously declared metavariables
(comma separated list of metavariable names), that can then be used in the
script code.  If the metavariables are not inherited from another rule,
they need to be used close together, ie not separated by ...

julia
